/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BlogId = string;
export interface BlogListing {
  'categories' : Array<string>,
  'featured' : [] | [BlogPost],
  'posts' : Array<BlogPost>,
}
export interface BlogPost {
  'id' : BlogId,
  'title' : string,
  'content' : string,
  'date' : Time,
  'author' : string,
  'category' : string,
  'image' : ExternalBlob,
}
export type Category = { 'necklaces' : null } |
  { 'earrings' : null } |
  { 'rings' : null } |
  { 'bracelets' : null };
export interface ContactMessage {
  'id' : string,
  'name' : string,
  'isRead' : boolean,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : [] | [string],
}
export type ExternalBlob = Uint8Array;
export interface FilteredProducts {
  'filters' : {
    'goldType' : [] | [GoldType],
    'stoneType' : [] | [StoneType],
    'sortBy' : [] | [SortOption],
    'priceRange' : [] | [[number, number]],
    'category' : [] | [Category],
  },
  'totalResults' : bigint,
  'products' : Array<Product>,
}
export type GoldType = { 'eighteenK' : null } |
  { 'fourteenK' : null };
export interface Order {
  'id' : string,
  'status' : OrderStatus,
  'customer' : Principal,
  'timestamp' : Time,
  'products' : Array<ProductId>,
}
export type OrderStatus = { 'shipped' : null } |
  { 'pending' : null } |
  { 'delivered' : null };
export interface Product {
  'id' : ProductId,
  'goldType' : GoldType,
  'stoneType' : StoneType,
  'title' : string,
  'description' : string,
  'isLimitedEdition' : boolean,
  'category' : Category,
  'isNew' : boolean,
  'price' : number,
  'images' : Array<ExternalBlob>,
}
export type ProductId = string;
export type SortOption = { 'priceLowToHigh' : null } |
  { 'newest' : null } |
  { 'priceHighToLow' : null };
export type StoneType = { 'ruby' : null } |
  { 'diamond' : null } |
  { 'sapphire' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'wishlist' : Array<ProductId>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBlogPost' : ActorMethod<[BlogPost], undefined>,
  'addContactMessage' : ActorMethod<[ContactMessage], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteBlogPost' : ActorMethod<[BlogId], undefined>,
  'deleteContactMessage' : ActorMethod<[string], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'filterProducts' : ActorMethod<
    [
      [] | [Category],
      [] | [[number, number]],
      [] | [GoldType],
      [] | [StoneType],
      [] | [SortOption],
    ],
    FilteredProducts
  >,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getBlogListing' : ActorMethod<[[] | [string]], BlogListing>,
  'getBlogPost' : ActorMethod<[BlogId], [] | [BlogPost]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getLimitedEditionProducts' : ActorMethod<[], Array<Product>>,
  'getNewestProducts' : ActorMethod<[], Array<Product>>,
  'getOrders' : ActorMethod<[Principal], Array<Order>>,
  'getProductDetails' : ActorMethod<[ProductId], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWishlist' : ActorMethod<[], Array<ProductId>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markMessageAsRead' : ActorMethod<[string], undefined>,
  'placeOrder' : ActorMethod<[Order], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleWishlist' : ActorMethod<[ProductId], undefined>,
  'updateBlogPost' : ActorMethod<[BlogPost], undefined>,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];