/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const BlogId = IDL.Text;
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const BlogPost = IDL.Record({
  'id' : BlogId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : Time,
  'author' : IDL.Text,
  'category' : IDL.Text,
  'image' : ExternalBlob,
});
export const ContactMessage = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'isRead' : IDL.Bool,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Opt(IDL.Text),
});
export const ProductId = IDL.Text;
export const GoldType = IDL.Variant({
  'eighteenK' : IDL.Null,
  'fourteenK' : IDL.Null,
});
export const StoneType = IDL.Variant({
  'ruby' : IDL.Null,
  'diamond' : IDL.Null,
  'sapphire' : IDL.Null,
});
export const Category = IDL.Variant({
  'necklaces' : IDL.Null,
  'earrings' : IDL.Null,
  'rings' : IDL.Null,
  'bracelets' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'goldType' : GoldType,
  'stoneType' : StoneType,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'isLimitedEdition' : IDL.Bool,
  'category' : Category,
  'isNew' : IDL.Bool,
  'price' : IDL.Float64,
  'images' : IDL.Vec(ExternalBlob),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SortOption = IDL.Variant({
  'priceLowToHigh' : IDL.Null,
  'newest' : IDL.Null,
  'priceHighToLow' : IDL.Null,
});
export const FilteredProducts = IDL.Record({
  'filters' : IDL.Record({
    'goldType' : IDL.Opt(GoldType),
    'stoneType' : IDL.Opt(StoneType),
    'sortBy' : IDL.Opt(SortOption),
    'priceRange' : IDL.Opt(IDL.Tuple(IDL.Float64, IDL.Float64)),
    'category' : IDL.Opt(Category),
  }),
  'totalResults' : IDL.Nat,
  'products' : IDL.Vec(Product),
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'status' : OrderStatus,
  'customer' : IDL.Principal,
  'timestamp' : Time,
  'products' : IDL.Vec(ProductId),
});
export const BlogListing = IDL.Record({
  'categories' : IDL.Vec(IDL.Text),
  'featured' : IDL.Opt(BlogPost),
  'posts' : IDL.Vec(BlogPost),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'wishlist' : IDL.Vec(ProductId),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBlogPost' : IDL.Func([BlogPost], [], []),
  'addContactMessage' : IDL.Func([ContactMessage], [], []),
  'addProduct' : IDL.Func([Product], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteBlogPost' : IDL.Func([BlogId], [], []),
  'deleteContactMessage' : IDL.Func([IDL.Text], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'filterProducts' : IDL.Func(
      [
        IDL.Opt(Category),
        IDL.Opt(IDL.Tuple(IDL.Float64, IDL.Float64)),
        IDL.Opt(GoldType),
        IDL.Opt(StoneType),
        IDL.Opt(SortOption),
      ],
      [FilteredProducts],
      ['query'],
    ),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getBlogListing' : IDL.Func([IDL.Opt(IDL.Text)], [BlogListing], ['query']),
  'getBlogPost' : IDL.Func([BlogId], [IDL.Opt(BlogPost)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getLimitedEditionProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getNewestProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
  'getProductDetails' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWishlist' : IDL.Func([], [IDL.Vec(ProductId)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markMessageAsRead' : IDL.Func([IDL.Text], [], []),
  'placeOrder' : IDL.Func([Order], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleWishlist' : IDL.Func([ProductId], [], []),
  'updateBlogPost' : IDL.Func([BlogPost], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const BlogId = IDL.Text;
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const BlogPost = IDL.Record({
    'id' : BlogId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : Time,
    'author' : IDL.Text,
    'category' : IDL.Text,
    'image' : ExternalBlob,
  });
  const ContactMessage = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'isRead' : IDL.Bool,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Opt(IDL.Text),
  });
  const ProductId = IDL.Text;
  const GoldType = IDL.Variant({
    'eighteenK' : IDL.Null,
    'fourteenK' : IDL.Null,
  });
  const StoneType = IDL.Variant({
    'ruby' : IDL.Null,
    'diamond' : IDL.Null,
    'sapphire' : IDL.Null,
  });
  const Category = IDL.Variant({
    'necklaces' : IDL.Null,
    'earrings' : IDL.Null,
    'rings' : IDL.Null,
    'bracelets' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'goldType' : GoldType,
    'stoneType' : StoneType,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'isLimitedEdition' : IDL.Bool,
    'category' : Category,
    'isNew' : IDL.Bool,
    'price' : IDL.Float64,
    'images' : IDL.Vec(ExternalBlob),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SortOption = IDL.Variant({
    'priceLowToHigh' : IDL.Null,
    'newest' : IDL.Null,
    'priceHighToLow' : IDL.Null,
  });
  const FilteredProducts = IDL.Record({
    'filters' : IDL.Record({
      'goldType' : IDL.Opt(GoldType),
      'stoneType' : IDL.Opt(StoneType),
      'sortBy' : IDL.Opt(SortOption),
      'priceRange' : IDL.Opt(IDL.Tuple(IDL.Float64, IDL.Float64)),
      'category' : IDL.Opt(Category),
    }),
    'totalResults' : IDL.Nat,
    'products' : IDL.Vec(Product),
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'status' : OrderStatus,
    'customer' : IDL.Principal,
    'timestamp' : Time,
    'products' : IDL.Vec(ProductId),
  });
  const BlogListing = IDL.Record({
    'categories' : IDL.Vec(IDL.Text),
    'featured' : IDL.Opt(BlogPost),
    'posts' : IDL.Vec(BlogPost),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'wishlist' : IDL.Vec(ProductId),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBlogPost' : IDL.Func([BlogPost], [], []),
    'addContactMessage' : IDL.Func([ContactMessage], [], []),
    'addProduct' : IDL.Func([Product], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteBlogPost' : IDL.Func([BlogId], [], []),
    'deleteContactMessage' : IDL.Func([IDL.Text], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'filterProducts' : IDL.Func(
        [
          IDL.Opt(Category),
          IDL.Opt(IDL.Tuple(IDL.Float64, IDL.Float64)),
          IDL.Opt(GoldType),
          IDL.Opt(StoneType),
          IDL.Opt(SortOption),
        ],
        [FilteredProducts],
        ['query'],
      ),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getBlogListing' : IDL.Func([IDL.Opt(IDL.Text)], [BlogListing], ['query']),
    'getBlogPost' : IDL.Func([BlogId], [IDL.Opt(BlogPost)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
    'getLimitedEditionProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getNewestProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
    'getProductDetails' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWishlist' : IDL.Func([], [IDL.Vec(ProductId)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markMessageAsRead' : IDL.Func([IDL.Text], [], []),
    'placeOrder' : IDL.Func([Order], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleWishlist' : IDL.Func([ProductId], [], []),
    'updateBlogPost' : IDL.Func([BlogPost], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
  });
};

export const init = ({ IDL }) => { return []; };