/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface BlogPost {
    id: BlogId;
    title: string;
    content: string;
    date: Time;
    author: string;
    category: string;
    image: ExternalBlob;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface FilteredProducts {
    filters: {
        goldType?: GoldType;
        stoneType?: StoneType;
        sortBy?: SortOption;
        priceRange?: [number, number];
        category?: Category;
    };
    totalResults: bigint;
    products: Array<Product>;
}
export interface Order {
    id: string;
    status: OrderStatus;
    customer: Principal;
    timestamp: Time;
    products: Array<ProductId>;
}
export interface ContactMessage {
    id: string;
    name: string;
    isRead: boolean;
    email: string;
    message: string;
    timestamp: Time;
    phone?: string;
}
export type BlogId = string;
export type ProductId = string;
export interface BlogListing {
    categories: Array<string>;
    featured?: BlogPost;
    posts: Array<BlogPost>;
}
export interface Product {
    id: ProductId;
    goldType: GoldType;
    stoneType: StoneType;
    title: string;
    description: string;
    isLimitedEdition: boolean;
    category: Category;
    isNew: boolean;
    price: number;
    images: Array<ExternalBlob>;
}
export interface UserProfile {
    name: string;
    email: string;
    wishlist: Array<ProductId>;
}
export enum Category {
    necklaces = "necklaces",
    earrings = "earrings",
    rings = "rings",
    bracelets = "bracelets"
}
export enum GoldType {
    eighteenK = "eighteenK",
    fourteenK = "fourteenK"
}
export enum OrderStatus {
    shipped = "shipped",
    pending = "pending",
    delivered = "delivered"
}
export enum SortOption {
    priceLowToHigh = "priceLowToHigh",
    newest = "newest",
    priceHighToLow = "priceHighToLow"
}
export enum StoneType {
    ruby = "ruby",
    diamond = "diamond",
    sapphire = "sapphire"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBlogPost(post: BlogPost): Promise<void>;
    addContactMessage(message: ContactMessage): Promise<void>;
    addProduct(product: Product): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteBlogPost(postId: BlogId): Promise<void>;
    deleteContactMessage(messageId: string): Promise<void>;
    deleteProduct(productId: ProductId): Promise<void>;
    filterProducts(category: Category | null, priceRange: [number, number] | null, goldType: GoldType | null, stoneType: StoneType | null, sortBy: SortOption | null): Promise<FilteredProducts>;
    getAllOrders(): Promise<Array<Order>>;
    getBlogListing(_category: string | null): Promise<BlogListing>;
    getBlogPost(_id: BlogId): Promise<BlogPost | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContactMessages(): Promise<Array<ContactMessage>>;
    getLimitedEditionProducts(): Promise<Array<Product>>;
    getNewestProducts(): Promise<Array<Product>>;
    getOrders(_userId: Principal): Promise<Array<Order>>;
    getProductDetails(_id: ProductId): Promise<Product | null>;
    getProducts(): Promise<Array<Product>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWishlist(): Promise<Array<ProductId>>;
    isCallerAdmin(): Promise<boolean>;
    markMessageAsRead(messageId: string): Promise<void>;
    placeOrder(order: Order): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    toggleWishlist(productId: ProductId): Promise<void>;
    updateBlogPost(post: BlogPost): Promise<void>;
    updateOrderStatus(orderId: string, status: OrderStatus): Promise<void>;
    updateProduct(product: Product): Promise<void>;
}
import type { BlogId as _BlogId, BlogListing as _BlogListing, BlogPost as _BlogPost, Category as _Category, ContactMessage as _ContactMessage, ExternalBlob as _ExternalBlob, FilteredProducts as _FilteredProducts, GoldType as _GoldType, Order as _Order, OrderStatus as _OrderStatus, Product as _Product, ProductId as _ProductId, SortOption as _SortOption, StoneType as _StoneType, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBlogPost(arg0: BlogPost): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBlogPost(await to_candid_BlogPost_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBlogPost(await to_candid_BlogPost_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addContactMessage(arg0: ContactMessage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addContactMessage(to_candid_ContactMessage_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addContactMessage(to_candid_ContactMessage_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(await to_candid_Product_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(await to_candid_Product_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n22(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n22(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteBlogPost(arg0: BlogId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBlogPost(arg0);
            return result;
        }
    }
    async deleteContactMessage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContactMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContactMessage(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: ProductId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async filterProducts(arg0: Category | null, arg1: [number, number] | null, arg2: GoldType | null, arg3: StoneType | null, arg4: SortOption | null): Promise<FilteredProducts> {
        if (this.processError) {
            try {
                const result = await this.actor.filterProducts(to_candid_opt_n24(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n27(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg4));
                return from_candid_FilteredProducts_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterProducts(to_candid_opt_n24(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n27(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg4));
            return from_candid_FilteredProducts_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogListing(arg0: string | null): Promise<BlogListing> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogListing(to_candid_opt_n57(this._uploadFile, this._downloadFile, arg0));
                return from_candid_BlogListing_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogListing(to_candid_opt_n57(this._uploadFile, this._downloadFile, arg0));
            return from_candid_BlogListing_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogPost(arg0: BlogId): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPost(arg0);
                return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPost(arg0);
            return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactMessages(): Promise<Array<ContactMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactMessages();
                return from_candid_vec_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactMessages();
            return from_candid_vec_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLimitedEditionProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLimitedEditionProducts();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLimitedEditionProducts();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNewestProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewestProducts();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewestProducts();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrders(arg0: Principal): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrders(arg0);
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrders(arg0);
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductDetails(arg0: ProductId): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductDetails(arg0);
                return from_candid_opt_n71(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductDetails(arg0);
            return from_candid_opt_n71(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWishlist(): Promise<Array<ProductId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWishlist();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWishlist();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markMessageAsRead(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markMessageAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markMessageAsRead(arg0);
            return result;
        }
    }
    async placeOrder(arg0: Order): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(to_candid_Order_n72(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(to_candid_Order_n72(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async toggleWishlist(arg0: ProductId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleWishlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleWishlist(arg0);
            return result;
        }
    }
    async updateBlogPost(arg0: BlogPost): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBlogPost(await to_candid_BlogPost_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBlogPost(await to_candid_BlogPost_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateOrderStatus(arg0: string, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n74(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n74(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(await to_candid_Product_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(await to_candid_Product_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
async function from_candid_BlogListing_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlogListing): Promise<BlogListing> {
    return await from_candid_record_n59(_uploadFile, _downloadFile, value);
}
async function from_candid_BlogPost_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlogPost): Promise<BlogPost> {
    return await from_candid_record_n62(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_ContactMessage_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContactMessage): ContactMessage {
    return from_candid_record_n69(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_FilteredProducts_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FilteredProducts): Promise<FilteredProducts> {
    return await from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_GoldType_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GoldType): GoldType {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n56(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n54(_uploadFile, _downloadFile, value);
}
async function from_candid_Product_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Promise<Product> {
    return await from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_SortOption_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SortOption): SortOption {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_StoneType_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StoneType): StoneType {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n66(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GoldType]): GoldType | null {
    return value.length === 0 ? null : from_candid_GoldType_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StoneType]): StoneType | null {
    return value.length === 0 ? null : from_candid_StoneType_n38(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SortOption]): SortOption | null {
    return value.length === 0 ? null : from_candid_SortOption_n41(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [[number, number]]): [number, number] | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Category]): Category | null {
    return value.length === 0 ? null : from_candid_Category_n45(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BlogPost]): Promise<BlogPost | null> {
    return value.length === 0 ? null : await from_candid_BlogPost_n61(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Promise<Product | null> {
    return value.length === 0 ? null : await from_candid_Product_n48(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    filters: {
        goldType: [] | [_GoldType];
        stoneType: [] | [_StoneType];
        sortBy: [] | [_SortOption];
        priceRange: [] | [[number, number]];
        category: [] | [_Category];
    };
    totalResults: bigint;
    products: Array<_Product>;
}): Promise<{
    filters: {
        goldType?: GoldType;
        stoneType?: StoneType;
        sortBy?: SortOption;
        priceRange?: [number, number];
        category?: Category;
    };
    totalResults: bigint;
    products: Array<Product>;
}> {
    return {
        filters: from_candid_record_n33(_uploadFile, _downloadFile, value.filters),
        totalResults: value.totalResults,
        products: await from_candid_vec_n47(_uploadFile, _downloadFile, value.products)
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    goldType: [] | [_GoldType];
    stoneType: [] | [_StoneType];
    sortBy: [] | [_SortOption];
    priceRange: [] | [[number, number]];
    category: [] | [_Category];
}): {
    goldType?: GoldType;
    stoneType?: StoneType;
    sortBy?: SortOption;
    priceRange?: [number, number];
    category?: Category;
} {
    return {
        goldType: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.goldType)),
        stoneType: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.stoneType)),
        sortBy: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.sortBy)),
        priceRange: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.priceRange)),
        category: record_opt_to_undefined(from_candid_opt_n44(_uploadFile, _downloadFile, value.category))
    };
}
async function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProductId;
    goldType: _GoldType;
    stoneType: _StoneType;
    title: string;
    description: string;
    isLimitedEdition: boolean;
    category: _Category;
    isNew: boolean;
    price: number;
    images: Array<_ExternalBlob>;
}): Promise<{
    id: ProductId;
    goldType: GoldType;
    stoneType: StoneType;
    title: string;
    description: string;
    isLimitedEdition: boolean;
    category: Category;
    isNew: boolean;
    price: number;
    images: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        goldType: from_candid_GoldType_n35(_uploadFile, _downloadFile, value.goldType),
        stoneType: from_candid_StoneType_n38(_uploadFile, _downloadFile, value.stoneType),
        title: value.title,
        description: value.description,
        isLimitedEdition: value.isLimitedEdition,
        category: from_candid_Category_n45(_uploadFile, _downloadFile, value.category),
        isNew: value.isNew,
        price: value.price,
        images: await from_candid_vec_n50(_uploadFile, _downloadFile, value.images)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _OrderStatus;
    customer: Principal;
    timestamp: _Time;
    products: Array<_ProductId>;
}): {
    id: string;
    status: OrderStatus;
    customer: Principal;
    timestamp: Time;
    products: Array<ProductId>;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n55(_uploadFile, _downloadFile, value.status),
        customer: value.customer,
        timestamp: value.timestamp,
        products: value.products
    };
}
async function from_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    categories: Array<string>;
    featured: [] | [_BlogPost];
    posts: Array<_BlogPost>;
}): Promise<{
    categories: Array<string>;
    featured?: BlogPost;
    posts: Array<BlogPost>;
}> {
    return {
        categories: value.categories,
        featured: record_opt_to_undefined(await from_candid_opt_n60(_uploadFile, _downloadFile, value.featured)),
        posts: await from_candid_vec_n63(_uploadFile, _downloadFile, value.posts)
    };
}
async function from_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BlogId;
    title: string;
    content: string;
    date: _Time;
    author: string;
    category: string;
    image: _ExternalBlob;
}): Promise<{
    id: BlogId;
    title: string;
    content: string;
    date: Time;
    author: string;
    category: string;
    image: ExternalBlob;
}> {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        date: value.date,
        author: value.author,
        category: value.category,
        image: await from_candid_ExternalBlob_n51(_uploadFile, _downloadFile, value.image)
    };
}
function from_candid_record_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    isRead: boolean;
    email: string;
    message: string;
    timestamp: _Time;
    phone: [] | [string];
}): {
    id: string;
    name: string;
    isRead: boolean;
    email: string;
    message: string;
    timestamp: Time;
    phone?: string;
} {
    return {
        id: value.id,
        name: value.name,
        isRead: value.isRead,
        email: value.email,
        message: value.message,
        timestamp: value.timestamp,
        phone: record_opt_to_undefined(from_candid_opt_n70(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    eighteenK: null;
} | {
    fourteenK: null;
}): GoldType {
    return "eighteenK" in value ? GoldType.eighteenK : "fourteenK" in value ? GoldType.fourteenK : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ruby: null;
} | {
    diamond: null;
} | {
    sapphire: null;
}): StoneType {
    return "ruby" in value ? StoneType.ruby : "diamond" in value ? StoneType.diamond : "sapphire" in value ? StoneType.sapphire : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    priceLowToHigh: null;
} | {
    newest: null;
} | {
    priceHighToLow: null;
}): SortOption {
    return "priceLowToHigh" in value ? SortOption.priceLowToHigh : "newest" in value ? SortOption.newest : "priceHighToLow" in value ? SortOption.priceHighToLow : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    necklaces: null;
} | {
    earrings: null;
} | {
    rings: null;
} | {
    bracelets: null;
}): Category {
    return "necklaces" in value ? Category.necklaces : "earrings" in value ? Category.earrings : "rings" in value ? Category.rings : "bracelets" in value ? Category.bracelets : value;
}
function from_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shipped: null;
} | {
    pending: null;
} | {
    delivered: null;
}): OrderStatus {
    return "shipped" in value ? OrderStatus.shipped : "pending" in value ? OrderStatus.pending : "delivered" in value ? OrderStatus.delivered : value;
}
function from_candid_variant_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Promise<Array<Product>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Product_n48(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n51(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n53(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BlogPost>): Promise<Array<BlogPost>> {
    return await Promise.all(value.map(async (x)=>await from_candid_BlogPost_n61(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContactMessage>): Array<ContactMessage> {
    return value.map((x)=>from_candid_ContactMessage_n68(_uploadFile, _downloadFile, x));
}
async function to_candid_BlogPost_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BlogPost): Promise<_BlogPost> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_Category_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_ContactMessage_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContactMessage): _ContactMessage {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_GoldType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GoldType): _GoldType {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n75(_uploadFile, _downloadFile, value);
}
function to_candid_Order_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Order): _Order {
    return to_candid_record_n73(_uploadFile, _downloadFile, value);
}
async function to_candid_Product_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Product): Promise<_Product> {
    return await to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_SortOption_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortOption): _SortOption {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_StoneType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StoneType): _StoneType {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category | null): [] | [_Category] {
    return value === null ? candid_none() : candid_some(to_candid_Category_n19(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [number, number] | null): [] | [[number, number]] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GoldType | null): [] | [_GoldType] {
    return value === null ? candid_none() : candid_some(to_candid_GoldType_n15(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StoneType | null): [] | [_StoneType] {
    return value === null ? candid_none() : candid_some(to_candid_StoneType_n17(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortOption | null): [] | [_SortOption] {
    return value === null ? candid_none() : candid_some(to_candid_SortOption_n29(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    isRead: boolean;
    email: string;
    message: string;
    timestamp: Time;
    phone?: string;
}): {
    id: string;
    name: string;
    isRead: boolean;
    email: string;
    message: string;
    timestamp: _Time;
    phone: [] | [string];
} {
    return {
        id: value.id,
        name: value.name,
        isRead: value.isRead,
        email: value.email,
        message: value.message,
        timestamp: value.timestamp,
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
async function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ProductId;
    goldType: GoldType;
    stoneType: StoneType;
    title: string;
    description: string;
    isLimitedEdition: boolean;
    category: Category;
    isNew: boolean;
    price: number;
    images: Array<ExternalBlob>;
}): Promise<{
    id: _ProductId;
    goldType: _GoldType;
    stoneType: _StoneType;
    title: string;
    description: string;
    isLimitedEdition: boolean;
    category: _Category;
    isNew: boolean;
    price: number;
    images: Array<_ExternalBlob>;
}> {
    return {
        id: value.id,
        goldType: to_candid_GoldType_n15(_uploadFile, _downloadFile, value.goldType),
        stoneType: to_candid_StoneType_n17(_uploadFile, _downloadFile, value.stoneType),
        title: value.title,
        description: value.description,
        isLimitedEdition: value.isLimitedEdition,
        category: to_candid_Category_n19(_uploadFile, _downloadFile, value.category),
        isNew: value.isNew,
        price: value.price,
        images: await to_candid_vec_n21(_uploadFile, _downloadFile, value.images)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: OrderStatus;
    customer: Principal;
    timestamp: Time;
    products: Array<ProductId>;
}): {
    id: string;
    status: _OrderStatus;
    customer: Principal;
    timestamp: _Time;
    products: Array<_ProductId>;
} {
    return {
        id: value.id,
        status: to_candid_OrderStatus_n74(_uploadFile, _downloadFile, value.status),
        customer: value.customer,
        timestamp: value.timestamp,
        products: value.products
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: BlogId;
    title: string;
    content: string;
    date: Time;
    author: string;
    category: string;
    image: ExternalBlob;
}): Promise<{
    id: _BlogId;
    title: string;
    content: string;
    date: _Time;
    author: string;
    category: string;
    image: _ExternalBlob;
}> {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        date: value.date,
        author: value.author,
        category: value.category,
        image: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.image)
    };
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GoldType): {
    eighteenK: null;
} | {
    fourteenK: null;
} {
    return value == GoldType.eighteenK ? {
        eighteenK: null
    } : value == GoldType.fourteenK ? {
        fourteenK: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StoneType): {
    ruby: null;
} | {
    diamond: null;
} | {
    sapphire: null;
} {
    return value == StoneType.ruby ? {
        ruby: null
    } : value == StoneType.diamond ? {
        diamond: null
    } : value == StoneType.sapphire ? {
        sapphire: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    necklaces: null;
} | {
    earrings: null;
} | {
    rings: null;
} | {
    bracelets: null;
} {
    return value == Category.necklaces ? {
        necklaces: null
    } : value == Category.earrings ? {
        earrings: null
    } : value == Category.rings ? {
        rings: null
    } : value == Category.bracelets ? {
        bracelets: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortOption): {
    priceLowToHigh: null;
} | {
    newest: null;
} | {
    priceHighToLow: null;
} {
    return value == SortOption.priceLowToHigh ? {
        priceLowToHigh: null
    } : value == SortOption.newest ? {
        newest: null
    } : value == SortOption.priceHighToLow ? {
        priceHighToLow: null
    } : value;
}
function to_candid_variant_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    shipped: null;
} | {
    pending: null;
} | {
    delivered: null;
} {
    return value == OrderStatus.shipped ? {
        shipped: null
    } : value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value;
}
async function to_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
